name: test
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs_version:
          - 25.2
          - 25.3
          - 26.1
          - 26.2
          - 26.3
          - 27.1
        include:
          - emacs_version: snapshot
            ignore_error: true
    steps:
      - name: Setup Emacs
        uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs_version }}

      - name: Setup Python (for Cask)
        uses: actions/setup-python@v2
        with:
          python-version: '3.6'
          architecture: 'x64'

      - name: Setup Cask
        uses: conao3/setup-cask@master
        with:
          version: "snapshot"

      - uses: actions/checkout@v2

      - name: Install
        id: install
        continue-on-error: ${{ matrix.ignore_error || matrix.ignore_error == '' }}
        run: |
          emacs --version
          cask build --verbose
          make build

      - name: Test
        if: steps.install.outcome == 'success' && steps.install.conclusion == 'success'
        run: |
          make test
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
          COVERALLS_PARALLEL: 1
          COVERALLS_FLAG_NAME: Emacs ${{ matrix.emacs_version }}

  finish:
    needs: build-and-test
    if: always()
    runs-on: ubuntu-latest
    steps:
      - run: curl "https://coveralls.io/webhook?repo_name=$GITHUB_REPOSITORY&repo_token=${{ secrets.GITHUB_TOKEN }}" -d "payload[build_num]=$GITHUB_RUN_NUMBER&payload[status]=done"
